services:
  ss-manager-api:
    container_name: ss-manager-api
    build: ./api/
    ports:
      - "8000:8000"
      - "9000-9020:9000-9020"
    volumes:
      - ./api/data:/app/data
    env_file:
      - ./api/.env