version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - ./app:/code/app
      - ./data/shadowsocks.db:/app/shadowsocks.db
    env_file:
      - .env