version: "3.9"

services:
  web:
    build: ./api/
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - ./api/app:/app
      - ./api/data/shadowsocks.db:/app/shadowsocks.db
    env_file:
      - ./api/.env